import Head from "next/head";
import Image from "next/image";
import { useUserContext } from "../context/userContext";

import Welcome from "../components/home/Welcome";
import AccordianPage from "../components/home/AccordianPage";
import Footer from "../components/Footer";
import { useRouter } from "next/router";
export default function Home() {
  const { user } = useUserContext();
  // console.log(user);
  const router = useRouter();
  if (user != null) {
    router.push("/home");
  }
  return (
    <div>
      <Head>
        <title>Netflix - Watch TV shows Online, Watch Movies Online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Welcome />
      <AccordianPage />
      <Footer />
    </div>
  );
}
