import Head from "next/head";
import Image from "next/image";
import { useUserContext } from "../context/userContext";

import Welcome from "../components/home/Welcome";
import AccordianPage from "../components/home/AccordianPage";
import Footer from "../components/Footer";
import { useRouter } from "next/router";
import { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css"; // You can also use <link> for styles
import Modal from "../components/Modal";
import DusraFooter from "../components/DusraFooter";
// ..
export default function Home() {
  const { user } = useUserContext();

  const router = useRouter();

  useEffect(() => {
    AOS.init();

    if (user != null) {
      router.push("/splash");
    }
  });
  return (
    <div className=" bg-black">
      <Head>
        <title>Netflix - Watch TV shows Online, Watch Movies Online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Welcome />
      <AccordianPage />
      <DusraFooter />
    </div>
  );
}
